version: "3.8"
services:
  postgres_database:
    image: postgres:16.2-alpine3.19
    container_name: postgres_database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
    ports:
      - ${POSTGRES_PORTS-5432:5432}
    volumes:
      - postgres_database:/var/lib/postgresql/data
    networks:
      - database-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_database:
    name: postgres_database

networks:
  database-network:
    driver: bridge 
    name: database-network
